### PR TITLE
New Education Template Added.

### PR DESCRIPTION
**Pull request by dreammehedi**
This pull request introduces a fully responsive education website template built using HTML and Tailwind CSS. The template features essential sections such as a hero banner, feature highlights, categorized content, top-rated tutorials, free certification lessons, testimonials, and brand showcases, all designed to enhance user engagement. The layout is optimized for various screen sizes, ensuring a seamless experience across devices. This addition serves as a versatile base for educational platforms, allowing for easy customization and expansion.

### CODE REVIEW

**Comment by sheik-mostafizur** [comment]
### Please fix this color contrast and check other parts

You can get help from these sites

[contrast-checker](https://coolors.co/contrast-checker/9ca4c2-ffffff)

image

**Comment by dreammehedi** [comment]
I solved this color contrast and checked other parts.

**Comment by sheik-mostafizur** [comment]
One more thing please see this and **add it** to your template for **identification**

image

**Comment by dreammehedi** [comment]
Template Identification Added.

**Comment by sheik-mostafizur** [comment]
### Congratulations on your first pull request merge in the main branch.

We will appreciate you.

**Pull request merged**
