### PR TITLE
lifeSchool file

### PR DESCRIPTION
**Pull request by minhazapon**
section-
1. navbar
2. hero 
3. school banner
4. school information
5. programs
6. uniqueness
7. practices
8. gallery
9. students and teacher
10. contact
11. address
lifeschool

### CODE REVIEW

**Comment by sheik-mostafizur** [comment]
I will check it after some times.

**Comment by minhazapon** [comment]
> I will check it after some times.

okay

**Comment by sheik-mostafizur** [comment]
Congratulation

**Comment by minhazapon** [comment]
> Congratulation

thanks

**Pull request merged**
