### PR TITLE
study nest landing page added

### PR DESCRIPTION
**Pull request by DeveloperImran1**

### CODE REVIEW

**Comment by sheik-mostafizur** [comment]
Please fix your image links and use only cdn

**Comment by DeveloperImran1** [comment]
Ok fine

**Comment by DeveloperImran1** [comment]
vaia, pul request hoisa ki

**Comment by sheik-mostafizur** [comment]
Please fix the background images in our system. We have some issues bg-[url()] so please this code

`html
  <div class="relative h-fit w-full py-8 lg:py-20">
      Background Image
      <div
        class="absolute inset-0 bg-gradient-to-t from-slate-950/50 to-slate-950/50"
      ></div>
      <div class="relative z-10 flex items-center justify-center h-full">
        
        <div>
          <h1 class="text-white text-4xl font-bold">Overlay Text</h1>
        </div>
      </div>
    </div>`

**Comment by sheik-mostafizur** [comment]
### Please knock me in [off-topic ](https://discord.gg/vnhqmn9mdj) there are a complex merge for some reason

**Pull request merged**
